[functions]
  # Includes "package.json" in the function bundle.
  node_bundler = "esbuild"
  included_files = ["package.json"]
  external_node_modules = ["@playwright/test", "playwright-core","astro"]

